### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by TheIntelloBox** [Gerrygames/ViaRewind#2]
https://media.discordapp.net/attachments/371405518482440194/402904304903520296/unknown.png?width=491&height=581

**Comment by Gerrygames** [comment]
This will be down to a plugin sending malformed json. Could you test without any other plugins?

**Comment by TheIntelloBox** [comment]
It works in 1.7 but not in 1.8 I'll test.

**Comment by Sytanicy** [comment]
I have the same join problem, also without plugins i cant join, i need to reconnect a few time's before i can join.

**Comment by Gerrygames** [comment]
Hm, I can't reproduce it. Can anyone provide their world for testing?

**Comment by TheIntelloBox** [comment]
My server has a texture pack maybe that's the problem ?

**Comment by Emafire003** [comment]
I have the same error too. But i can't delete any plugin. I removed temporaney the ViaBackwards plugin i the bungee and since this mornig i could join the hub with 1.8-1.12.2 versions but in the others servers i couldn't join. Today i can't join with more versions except the jar version. I can provide my world of the hub and its plugins (not setted).

**Comment by Emafire003** [comment]
Idem for the bungee
